package com.gonzobeans.blackjack.game;

public enum Action {
    NONE_SELECTED, SIT_AT_TABLE, LEAVE_TABLE, BET, HIT, STAY,  DOUBLE_DOWN, SPLIT, ACCEPT_INSURANCE,
    DECLINE_INSURANCE, NOT_AVAILABLE
}
